"""allocation view

Revision ID: 256fcbef55e3
Revises: d4bb98f59a35
Create Date: 2023-09-23 10:36:23.666742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '256fcbef55e3'
down_revision: Union[str, None] = 'd4bb98f59a35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allocations_view',
    sa.Column('orderid', sa.String(length=255), nullable=True),
    sa.Column('sku', sa.String(length=255), nullable=True),
    sa.Column('batchref', sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('allocations_view')
    # ### end Alembic commands ###
